## Introduction to numpy:

<p style="font-family: Arial; font-size:1.25em;color:#2462C0; font-style:bold"><br>
Package for scientific computing with Python
</p><br>

Numerical Python, or "Numpy" for short, is a foundational package on which many of the most common data science packages are built.  Numpy provides us with high performance multi-dimensional arrays which we can use as vectors or matrices.  

The key features of numpy are:

- ndarrays: n-dimensional arrays of the same data type which are fast and space-efficient.  There are a number of built-in methods for ndarrays which allow for rapid processing of data without using loops (e.g., compute the mean).
- Broadcasting: a useful tool which defines implicit behavior between multi-dimensional arrays of different sizes.
- Vectorization: enables numeric operations on ndarrays.
- Input/Output: simplifies reading and writing of data from/to file.

<b>Additional Recommended Resources:</b><br>
<a href="https://docs.scipy.org/doc/numpy/reference/">Numpy Documentation</a><br>
<i>Python for Data Analysis</i> by Wes McKinney<br>
<i>Python Data science Handbook</i> by Jake VanderPlas



### Getting started with ndarray

**ndarrays** are time and space-efficient multidimensional arrays at the core of numpy.  Like the data structures in Week 2, let's get started by creating ndarrays using the numpy package.

How to create Rank 1 numpy arrays:

In [ ]:
import numpy as np

an_array = np.array([3, 33, 333])  # Create a rank 1 array

print(type(an_array))              # The type of an ndarray is: "<class 'numpy.ndarray'>"

<class 'numpy.ndarray'>


In [ ]:
an_array

array([  3,  33, 333])

In [ ]:
# test the shape of the array we just created, it should have just one dimension (Rank 1)
print(an_array.shape)

(3,)


In [ ]:
# because this is a 1-rank array, we need only one index to accesss each element
an_array[0]

3

In [ ]:
an_array[2]

333

In [ ]:
an_array[1]=555

In [ ]:
an_array

array([  3, 555, 333])

In [ ]:
an_array[0] =888            # ndarrays are mutable, here we change an element of the array

print(an_array)

[888  33 333]





How to create a Rank 2 numpy array:

A rank 2 **ndarray** is one with two dimensions.  Notice the format below of [ [row] , [row] ].  2 dimensional arrays are great for representing matrices which are often useful in data science.

In [ ]:
another = np.array([[11,12,13],[21,22,23]])   # Create a rank 2 array

print(another)  # print the array

print("The shape is 2 rows, 3 columns: ", another.shape)  # rows x columns                   

print("Accessing elements [0,0], [0,1], and [1,0] of the ndarray: ", another[0, 0], ", ",another[0, 1],", ", another[1, 0])

[[11 12 13]
 [21 22 23]]
The shape is 2 rows, 3 columns:  (2, 3)
Accessing elements [0,0], [0,1], and [1,0] of the ndarray:  11 ,  12 ,  21


<p style="font-family: Arial; font-size:1.75em;color:#2462C0; font-style:bold"><br>

There are many way to create numpy arrays:
</p>

Here we create a number of different size arrays with different shapes and different pre-filled values.  numpy has a number of built in methods which help us quickly and easily create multidimensional arrays.

In [ ]:
import numpy as np

# create a 2x2 array of zeros
ex1 = np.zeros((2,2))      
print(ex1)                              

[[0. 0.]
 [0. 0.]]


In [ ]:
# create a 2x2 array filled with 9.0
ex2 = np.full((2,2), 9.0)  
print(ex2)   

[[9. 9.]
 [9. 9.]]


In [ ]:
# create a 2x2 matrix with the diagonal 1s and the others 0
ex3 = np.eye(3,3)
print(ex3)  

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [ ]:
# create an array of ones
ex4 = np.ones((3,2))
print(ex4)    

[[1. 1.]
 [1. 1.]
 [1. 1.]]


In [ ]:
# notice that the above ndarray (ex4) is actually rank 2, it is a 2x1 array
print(ex4.shape)

# which means we need to use two indexes to access an element
print()
print(ex4[0,1])

(1, 2)

1.0


In [ ]:
# create an array of random floats between 0 and 1
ex5 = np.random.random((2,2))
print(ex5)    

[[0.67151858 0.23889649]
 [0.07882758 0.9568015 ]]


### Array Indexing

#### Slice indexing:

Similar to the use of slice indexing with lists and strings, we can use slice indexing to pull out sub-regions of ndarrays.

In [ ]:
import numpy as np

# Rank 2 array of shape (3, 4)
an_array = np.array([[11,12,13,14], [21,22,23,24], [31,32,33,34]])
print(an_array)

[[11 12 13 14]
 [21 22 23 24]
 [31 32 33 34]]


Use array slicing to get a subarray consisting of the first 2 rows x 2 columns.

In [ ]:
a_slice = an_array[1:3]
print(a_slice)

[[21 22 23 24]
 [31 32 33 34]]


When you modify a slice, you actually modify the underlying array.

In [ ]:
print("Before:", an_array[0, 1])   #inspect the element at 0, 1  
a_slice[0, 0] = 1000    # a_slice[0, 0] is the same piece of data as an_array[0, 1]
print("After:", an_array[0, 1])    

Before: 12
After: 1000


<p style="font-family: Arial; font-size:1.75em;color:#2462C0; font-style:bold"><br>

Use both integer indexing & slice indexing
</p>

We can use combinations of integer indexing and slice indexing to create different shaped matrices.

In [ ]:
# Create a Rank 2 array of shape (3, 4)
an_array = np.array([[11,12,13,14], [21,22,23,24], [31,32,33,34]])
print(an_array)

NameError: name 'np' is not defined

In [ ]:
# Using both integer indexing & slicing generates an array of lower rank
row_rank1 = an_array[2:, ]    # Rank 1 view 

#print(row_rank1, row_rank1.shape)  # notice only a single []

In [ ]:
row_rank1

array([[31, 32, 33, 34]])

In [ ]:
row_rank1.shape

(3, 4)

In [ ]:
# Slicing alone: generates an array of the same rank as the an_array
row_rank2 = an_array[1:2, ]  # Rank 2 view 


#print(row_rank2, row_rank2.shape)   # Notice the [[ ]]

In [ ]:
row_rank2

array([[21, 22, 23, 24]])

In [ ]:
#We can do the same thing for columns of an array:

print()
col_rank1 = an_array[:, 2]
#col_rank2 = an_array[:, 1:2]

#col_rank2
col_rank1

#print(col_rank1, col_rank1.shape)  # Rank 1
#print()
#print(col_rank2, col_rank2.shape)  # Rank 2

array([13, 23, 33])

In [ ]:
col_rank1

array([12, 22, 32])

In [ ]:
col_rank2

array([[12],
       [22],
       [32]])

In [ ]:
col_rank2.shape

(3, 1)

<p style="font-family: Arial; font-size:1.75em;color:#2462C0; font-style:bold"><br>

Array Indexing for changing elements:
</p>

Sometimes it's useful to use an array of indexes to access or change elements.

In [ ]:
# Create a new array
an_array = np.array([[11,12,13], [21,22,23], [31,32,33], [41,42,43]])

print('Original Array:')
print(an_array)

Original Array:
[[11 12 13]
 [21 22 23]
 [31 32 33]
 [41 42 43]]


In [ ]:
# Create an array of indices
col_indices = np.array([0, 1, 2, 0])
print('\nCol indices picked : ', col_indices)

row_indices = np.arange(5)
print('\nRows indices picked : ', row_indices)


Col indices picked :  [0 1 2 0]

Rows indices picked :  [0 1 2 3 4]


In [ ]:
# Examine the pairings of row_indices and col_indices.  These are the elements we'll change next.
for row,col in zip(row_indices,col_indices):
    print(row, ", ",col)

0 ,  0
1 ,  1
2 ,  2
3 ,  0


In [ ]:
# Select one element from each row
print('Values in the array at those indices: ',an_array[row_indices, col_indices])

IndexError: shape mismatch: indexing arrays could not be broadcast together with shapes (5,) (4,) 

In [ ]:
# Change one element from each row using the indices selected
an_array[row_indices, col_indices] += 100000

print('\nChanged Array:')
print(an_array)

IndexError: shape mismatch: indexing arrays could not be broadcast together with shapes (5,) (4,) 

<p style="font-family: Arial; font-size:2.75em;color:purple; font-style:bold"><br>
Boolean Indexing

<br><br></p>
<p style="font-family: Arial; font-size:1.75em;color:#2462C0; font-style:bold"><br>

Array Indexing for changing elements:
</p>

In [ ]:
# create a 3x2 array
an_array = np.array([[11,12], [21, 22], [31, 32]])
print(an_array)

[[11 12]
 [21 22]
 [31 32]]


In [ ]:
# create a filter which will be boolean values for whether each element meets this condition
filter = (an_array > 15)
filter

array([[False, False],
       [ True,  True],
       [ True,  True]])

In [ ]:
print(an_array[filter])

[21 22 31 32]


In [ ]:
filter

array([[False, False],
       [ True,  True],
       [ True,  True]])

Notice that the filter is a same size ndarray as an_array which is filled with True for each element whose corresponding element in an_array which is greater than 15 and False for those elements whose value is less than 15.

In [ ]:
# we can now select just those elements which meet that criteria
print(an_array[filter])

[21 22 31 32]


In [ ]:
# For short, we could have just used the approach below without the need for the separate filter array.

an_array[(an_array % 2 == 0)]

array([12, 22, 32])

What is particularly useful is that we can actually change elements in the array applying a similar logical filter.  Let's add 100 to all the even values.

In [ ]:
an_array[an_array % 2 == 0] +=100
print(an_array)

<p style="font-family: Arial; font-size:2.75em;color:purple; font-style:bold"><br>

Datatypes and Array Operations
<br><br></p>

<p style="font-family: Arial; font-size:1.75em;color:#2462C0; font-style:bold"><br>

Datatypes:
</p>

In [ ]:
ex1 = np.array([11, 12],dtype=np.float64) # Python assigns the  data type
print(ex1.dtype)

float64


In [ ]:
ex1

array([11., 12.])

In [ ]:
ex2 = np.array([11.0, 12.0]) # Python assigns the  data type
print(ex2.dtype)

float64


In [ ]:
ex1

array([11., 12.])

In [ ]:
ex3 = np.array([11, 21], dtype=np.int64) #You can also tell Python the  data type
print(ex3.dtype)

int64


In [ ]:
# you can use this to force floats into integers (using floor function)
ex4 = np.array([11.1,12.7], dtype=np.int64)
print(ex4.dtype)
print()
print(ex4)

int64

[11 12]


In [ ]:
ex3

array([11, 21], dtype=int64)

In [ ]:
# you can use this to force integers into floats if you anticipate
# the values may change to floats later
ex5 = np.array([11, 21], dtype=np.float64)
print(ex5.dtype)
print()
print(ex5)

float64

[11. 21.]


<p style="font-family: Arial; font-size:1.75em;color:#2462C0; font-style:bold"><br>

Arithmetic Array Operations:

</p>

In [ ]:
x = np.array([[111,112],[121,122]], dtype=np.int)
y = np.array([[211.1,212.1],[221.1,222.1]], dtype=np.float64)

print(x)
print()
print(y)

[[111 112]
 [121 122]]

[[211.1 212.1]
 [221.1 222.1]]


In [ ]:
# add
#print(x + y)         # The plus sign works
print()
print(np.add(x, y))  # so does the numpy function "add"


[[322.1 324.1]
 [342.1 344.1]]


In [ ]:
z=print(x+y)

[[322.1 324.1]
 [342.1 344.1]]


In [ ]:
# subtract
print(x - y)
print()
print(np.subtract(x, y))

[[-100.1 -100.1]
 [-100.1 -100.1]]

[[-100.1 -100.1]
 [-100.1 -100.1]]


In [ ]:
# multiply
print(x * y)
print()
print(np.multiply(x, y))

[[23432.1 23755.2]
 [26753.1 27096.2]]

[[23432.1 23755.2]
 [26753.1 27096.2]]


In [ ]:
# divide
print(x / y)
print()
print(np.divide(x, y))

In [ ]:
# square root
print(np.sqrt(x))

[[10.53565375 10.58300524]
 [11.         11.04536102]]


In [ ]:
# exponent (e ** x)
print(np.exp(x))

[[1.60948707e+48 4.37503945e+48]
 [3.54513118e+52 9.63666567e+52]]


<p style="font-family: Arial; font-size:2.75em;color:purple; font-style:bold"><br>

Statistical Methods, Sorting, and <br> <br> Set Operations:
<br><br>
</p>

<p style="font-family: Arial; font-size:1.75em;color:#2462C0; font-style:bold"><br>

Basic Statistical Operations:
</p>

In [ ]:
# setup a random 2 x 4 matrix
arr = 10 * np.random.randn(2,5)
print(arr)

[[-11.90561658   6.29218178  -3.31007677  -4.38045289  -0.5198023 ]
 [ 13.60571057   6.89600384  -3.16450941 -10.96867918   3.66549265]]


In [ ]:
# compute the mean for all elements
print(arr.mean())

-0.3789748289670082


In [ ]:
# compute the means by row
print(arr.mean(axis = 1))

[-2.76475335  2.00680369]


In [ ]:
# compute the means by column
print(arr.mean(axis = 0))

[ 0.85004699  6.59409281 -3.23729309 -7.67456604  1.57284518]


In [ ]:
# sum all the elements
print(arr.sum())

-3.789748289670082


In [ ]:
# compute the medians
print(np.median(arr, axis = 1))

[2.2223418  2.71096331]


<p style="font-family: Arial; font-size:1.75em;color:#2462C0; font-style:bold"><br>

Sorting:
</p>


In [ ]:
# create a 10 element array of randoms
unsorted = np.random.randn(10)

print(unsorted)

[ 0.74769332  1.34100457  0.27374608 -0.19789724 -0.88918003 -0.40927734
 -1.00402086  0.61821472  0.30337198  1.17205879]


In [ ]:
# create copy and sort
sorted = np.array(unsorted)
sorted.sort()

print(sorted)
print()
print(unsorted)

[-1.00402086 -0.88918003 -0.40927734 -0.19789724  0.27374608  0.30337198
  0.61821472  0.74769332  1.17205879  1.34100457]

[ 0.74769332  1.34100457  0.27374608 -0.19789724 -0.88918003 -0.40927734
 -1.00402086  0.61821472  0.30337198  1.17205879]


In [ ]:
# inplace sorting
unsorted.sort() 

print(unsorted)

[-1.81543993 -1.15780154 -0.81333916 -0.24468951 -0.23931885 -0.12686776
 -0.08941569  0.79029364  0.9128369   1.16449928]


<p style="font-family: Arial; font-size:1.75em;color:#2462C0; font-style:bold"><br>

Finding Unique elements:
</p>

In [ ]:
array = np.array([1,2,1,4,2,1,4,2])

print(np.unique(array))

[1 2 4]


<p style="font-family: Arial; font-size:1.75em;color:#2462C0; font-style:bold"><br>

Set Operations with np.array data type:
</p>

In [ ]:
s1 = np.array(['desk','chair','bulb'])
s2 = np.array(['lamp','bulb','chair'])
print(s1, s2)

['desk' 'chair' 'bulb'] ['lamp' 'bulb' 'chair']


In [ ]:
print( np.intersect1d(s1, s2) ) 

['bulb' 'chair']


In [ ]:
print( np.union1d(s1, s2) )

['bulb' 'chair' 'desk' 'lamp']


In [ ]:
print( np.setdiff1d(s2, s1) )# elements in s1 that are not in s2

['lamp']


In [ ]:
print( np.in1d(s1, s2) )#which element of s1 is also in s2

[False  True  True]


<p style="font-family: Arial; font-size:2.75em;color:purple; font-style:bold"><br>

Broadcasting:
<br><br>
</p>

Introduction to broadcasting. <br>
For more details, please see: <br>
https://docs.scipy.org/doc/numpy-1.10.1/user/basics.broadcasting.html

In [ ]:
import numpy as np

start = np.zeros((4,3))
print(start)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [ ]:
# create a rank 1 ndarray with 3 values
add_rows = np.array([1, 0, 2])
print(add_rows)

[1 0 2]


In [ ]:
y = start + add_rows  # add to each row of 'start' using broadcasting
print(y)

[[1. 0. 2.]
 [1. 0. 2.]
 [1. 0. 2.]
 [1. 0. 2.]]


In [ ]:
# create an ndarray which is 4 x 1 to broadcast across columns
add_cols = np.array([[0,1,2,3]])
add_cols = add_cols.T

print(add_cols)

[[0]
 [1]
 [2]
 [3]]


In [ ]:
# add to each column of 'start' using broadcasting
y = start + add_cols 
print(y)

NameError: name 'start' is not defined

In [ ]:
# this will just broadcast in both dimensions
add_scalar = np.array([1])  
print(start+add_scalar)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


Example from the slides:

In [ ]:
# create our 3x4 matrix
arrA = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
print(arrA)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [ ]:
# create our 1x4 array
arrB = [0,1,0,2]
print(arrB)

[0, 1, 0, 2]


In [ ]:
# add the two together using broadcasting
print(arrA + arrB)

[[ 1  3  3  6]
 [ 5  7  7 10]
 [ 9 11 11 14]]


<p style="font-family: Arial; font-size:2.75em;color:purple; font-style:bold"><br>

Speedtest: ndarrays vs lists
<br><br>
</p>

First setup paramaters for the speed test. We'll be testing time to sum elements in an ndarray versus a list.

In [ ]:
from numpy import arange
from timeit import Timer

size    = 1000000
timeits = 1000

In [ ]:
# create the ndarray with values 0,1,2...,size-1
nd_array = arange(size)
print( type(nd_array) )

<class 'numpy.ndarray'>


In [ ]:
# timer expects the operation as a parameter, 
# here we pass nd_array.sum()
timer_numpy = Timer("nd_array.sum()", "from __main__ import nd_array")

print("Time taken by numpy ndarray: %f seconds" % 
      (timer_numpy.timeit(timeits)/timeits))

Time taken by numpy ndarray: 0.001543 seconds


In [ ]:
# create the list with values 0,1,2...,size-1
a_list = list(range(size))
print (type(a_list) )

<class 'list'>


In [ ]:
# timer expects the operation as a parameter, here we pass sum(a_list)
timer_list = Timer("sum(a_list)", "from __main__ import a_list")

print("Time taken by list:  %f seconds" % 
      (timer_list.timeit(timeits)/timeits))

Time taken by list:  0.076092 seconds


<p style="font-family: Arial; font-size:2.75em;color:purple; font-style:bold"><br>

Read or Write to Disk:
<br><br>
</p>

<p style="font-family: Arial; font-size:1.3em;color:#2462C0; font-style:bold"><br>

Binary Format:</p>

In [ ]:
x = np.array([ 23.23, 24.24] )

In [ ]:
np.save('an_array', x)

In [ ]:
np.load('an_array.npy')

array([23.23, 24.24])

<p style="font-family: Arial; font-size:1.3em;color:#2462C0; font-style:bold"><br>

Text Format:</p>

In [ ]:
np.savetxt('array.txt', X=x, delimiter=',')

In [ ]:
!cat array.txt

'cat' is not recognized as an internal or external command,
operable program or batch file.


In [ ]:
np.loadtxt('array.txt', delimiter=',')

array([23.23, 24.24])

<p style="font-family: Arial; font-size:2.75em;color:purple; font-style:bold"><br>

Additional Common ndarray Operations
<br><br></p>

<p style="font-family: Arial; font-size:1.75em;color:#2462C0; font-style:bold"><br>

Dot Product on Matrices and Inner Product on Vectors:

</p>

In [ ]:
# determine the dot product of two matrices
x2d = np.array([[1,1],[1,1]])
y2d = np.array([[4,2],[2,2]])

print(y2d.dot(x2d))
print()
print(np.dot(x2d, y2d))

[[6 6]
 [4 4]]

[[6 4]
 [6 4]]


In [ ]:
# determine the inner product of two vectors
a1d = np.array([9 , 9 ])
b1d = np.array([10, 10])

print(a1d.dot(b1d))
print()
print(np.dot(a1d, b1d))

180

180


In [ ]:
# dot produce on an array and vector
print(x2d.dot(a1d))
print()
print(np.dot(x2d, a1d))

<p style="font-family: Arial; font-size:1.75em;color:#2462C0; font-style:bold"><br>

Sum:
</p>

In [ ]:
# sum elements in the array
ex1 = np.array([[5555,12],[21,22]])

print(np.sum(ex1))          # add all members

5610


In [ ]:
z

array([[5555,   12],
       [  21,   22]])

In [ ]:
print(np.sum(ex1, axis=0))  # columnwise sum

[5576   34]


In [ ]:
print(np.sum(ex1, axis=1))  # rowwise sum

[5567   43]


<p style="font-family: Arial; font-size:1.75em;color:#2462C0; font-style:bold"><br>

Element-wise Functions: </p>

For example, let's compare two arrays values to get the maximum of each.

In [ ]:
# random array
x = np.random.randn(8)
x

array([ 0.23123575, -0.13964506,  0.54642902,  2.13166033,  0.70042187,
       -1.80911084,  0.45461145,  0.95425846])

In [ ]:
# another random array
y = np.random.randn(8)
y

array([ 0.06024981, -2.61240616,  2.24486972,  0.24916628, -1.75689146,
        0.19773358, -1.6338511 , -0.44758649])

In [ ]:
# returns element wise maximum between two arrays

np.maximum(x, y)

array([ 0.23123575, -0.13964506,  2.24486972,  2.13166033,  0.70042187,
        0.19773358,  0.45461145,  0.95425846])

<p style="font-family: Arial; font-size:1.75em;color:#2462C0; font-style:bold"><br>

Reshaping array:
</p>

In [ ]:
# grab values from 0 through 19 in an array
arr = np.arange(20)
print(arr)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]


In [ ]:
# reshape to be a 4 x 5 matrix
arr.reshape(4,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

<p style="font-family: Arial; font-size:1.75em;color:#2462C0; font-style:bold"><br>

Transpose:

</p>

In [ ]:
# transpose
ex1 = np.array([[11,12],[21,22]])

ex1.T

array([[11, 21],
       [12, 22]])

<p style="font-family: Arial; font-size:1.75em;color:#2462C0; font-style:bold"><br>

Indexing using where():</p>

In [ ]:
x_1 = np.array([1,2,3,4,5])

y_1 = np.array([11,22,33,44,55])

filter = np.array([True, False, True, False, True])

In [ ]:
out = np.where(filter, x_1, y_1)
print(out)

[ 1 22  3 44  5]


In [ ]:
mat = np.random.rand(5,5)
mat

array([[0.83435965, 0.81795061, 0.80680345, 0.65334537, 0.00157104],
       [0.8459081 , 0.14174351, 0.78561815, 0.31301464, 0.25460907],
       [0.49992058, 0.35152987, 0.84053128, 0.89910021, 0.25543315],
       [0.06302714, 0.64853798, 0.20181108, 0.18975514, 0.80096362],
       [0.2604743 , 0.12362859, 0.02954779, 0.45736027, 0.85421247]])

In [ ]:
np.where( mat > 0.5, 1000, -1)

<p style="font-family: Arial; font-size:1.75em;color:#2462C0; font-style:bold"><br>

"any" or "all" conditionals:</p>

In [ ]:
arr_bools = np.array([ True, False, True, True, False ])

In [ ]:
arr_bools.any()

In [ ]:
arr_bools.all()

<p style="font-family: Arial; font-size:1.75em;color:#2462C0; font-style:bold"><br>

Random Number Generation:
</p>

In [ ]:
Y = np.random.normal(size = (1,5))[0]
print(Y)

[-2.32636893 -0.97813992  0.07156108 -0.44156578 -0.04316732]


In [ ]:
Z = np.random.randint(low=2,high=50,size=4)
print(Z)

[15 18 14 28]


In [ ]:
np.random.permutation(Z) #return a new ordering of elements in Z

array([18, 15, 28, 14])

In [ ]:
np.random.uniform(size=4) #uniform distribution

array([0.36789357, 0.86931939, 0.40167529, 0.4024343 ])

In [ ]:
np.random.normal(size=4) #normal distribution

array([ 2.05395666,  0.49188842, -0.1582189 , -0.30197801])

<p style="font-family: Arial; font-size:1.75em;color:#2462C0; font-style:bold"><br>

Merging data sets:
</p>

In [ ]:
K = np.random.randint(low=2,high=50,size=(2,2))
print(K)

print()
M = np.random.randint(low=2,high=50,size=(2,2))
print(M)

NameError: name 'np' is not defined

In [ ]:
np.vstack((K,M))

array([[ 9, 41],
       [26, 12],
       [ 7, 17],
       [34, 23]])

In [ ]:
np.hstack((K,M))

array([[ 9, 41,  7, 17],
       [26, 12, 34, 23]])

In [ ]:
np.concatenate([K, M], axis = 0)

NameError: name 'np' is not defined

In [ ]:
np.concatenate([K, M.T], axis = 1)

array([[11, 35, 28, 12],
       [15, 42, 37, 44]])